if game.PlaceId == 2990100290 then
    loadstring(game:HttpGet("https://pastebin.com/raw/54v2dCWG", true))()
elseif game.PlaceId == 4628853904 then
    loadstring(game:HttpGet("https://pastebin.com/raw/vqhV70rY", true))()
elseif game.PlaceId == 3917106969 then
    loadstring(game:HttpGet("https://pastebin.com/raw/wvbqMHqP", true))()
elseif game.PlaceId == 3218530770 then
    loadstring(game:HttpGet("https://pastebin.com/raw/wvbqMHqP", true))()
elseif game.PlaceId == 3933064259 then
    loadstring(game:HttpGet("https://pastebin.com/raw/wvbqMHqP", true))()
elseif game.PlaceId == 3800652960 then
    loadstring(game:HttpGet("https://pastebin.com/raw/wvbqMHqP", true))()
elseif game.PlaceId == 4587322792 then
    loadstring(game:HttpGet("https://pastebin.com/raw/wvbqMHqP", true))()
elseif game.PlaceId == 4638348126  then
    loadstring(game:HttpGet("https://pastebin.com/raw/wvbqMHqP", true))()
elseif game.PlaceId == 4660023857 then
    loadstring(game:HttpGet("https://pastebin.com/raw/wvbqMHqP", true))()
end